### ISSUE TITLE
编译main.tex文件失败

### ISSUE THREAD

**Issue by ShivangSong** [Tang1705/BJTU-Beamer#1]
学长你好，我在使用你写的 `BJTU-Beamer` 模板时，按照手册操作，在编译 `main.tex` 出现了以下错误，报错信息是 ``./main.tex:41: Package PGF Math Error: Unknown operator `o' or `of' (in '1.5mm of hammer')``，并且它会在每个 `\end{frame}` 后输出一次这个错误，我在互联网上也没有找到类似错误，因此来询问学长，希望学长可以帮忙回答，谢谢。
我的操作系统是 `Windows 10`，`TeX` 发行版是 `TeXLive2022`。

**Comment by Tang1705** [comment]
感谢使用和提出 issue，我本地编写的过程中确实没有发现这问题。

放到 overleaf 后确实会有你遇到的 error message，解决只需添加 \usetikzlibrary{positioning} 即可，后续我也会更新上来。
